name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.6"

      - name: Install dependencies
        run: flutter pub get

      - name: Run lint
        run: flutter analyze

  android-build:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.6"

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

  ios-build:
    runs-on: macos-latest
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.6"

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --no-codesign

      - name: Upload iOS Build
        uses: actions/upload-artifact@v2
        with:
          name: ios-build
          path: build/ios/iphoneos

  commit-style:
    needs: lint
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v4
        with:
          config: conventional

  label-pr:
    needs: lint
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Assign label based on changes
        uses: actions/github-script@v6
        with:
          script: |
            const additions = context.payload.pull_request.additions;
            const deletions = context.payload.pull_request.deletions;
            const linesChanged = additions + deletions;
            let label = '';

            if (linesChanged <= 9) {
              label = 'size: XS';
            } else if (linesChanged <= 29) {
              label = 'size: S';
            } else if (linesChanged <= 99) {
              label = 'size: M';
            } else if (linesChanged <= 499) {
              label = 'size: L';
            } else if (linesChanged <= 999) {
              label = 'size: XL';
            } else {
              label = 'size: XXL';
            }

            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: [label]
            });
